replicaCount: 3

image:
  repository: parthsinha18/parth-port-k8s
  tag: latest
  pullPolicy: Always

services:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: pksinha.co.uk
      paths:
        - path: /
          pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: {}
affinity: {}