apiVersion: apps/v1
kind: Deployment
metadata:
  name: parth-port-k8s

spec:
  replicas: 3
  selector:
    matchLabels:
      app: parth-port-k8s
  template:
    metadata:
      labels:
        app: parth-port-k8s
    spec:
      containers:
        - name: parth-port-k8s
          image: parthsinha18/parth-port-k8s
          ports:
            - containerPort: 3000

