apiVersion: apps/v1
kind: Deployment
metadata:
  name: parth-nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parth-nextjs-app
  template:
    metadata:
      labels:
        app: parth-nextjs-app
    spec:
      containers:
        - name: parth-nextjs-app
          image: parthsinha18/parth-port-k8s
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 3000
