apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parth-prod-ingress

spec:
  rules:
    - host: kube.pksinha.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parth-port-k8s  # Updated service name
                port:
                  number: 80
