apiVersion: v1
kind: Service
metadata:
  name: parth-nextjs-service
spec:
  selector:
    app: parth-nextjs-app
  ports:
    - protocol: TCP
      port: 80  # External port for access (can be changed)
      targetPort: 3000  # Port exposed by the container
  type: NodePort  # Adjust type based on your needs (e.g. NodePort)
