apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parth-port-helm.fullname" . }}
  labels:
    {{- include "parth-port-helm.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "parth-port-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "parth-port-helm.selectorLabels".  | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 30
            periodSeconds: 10