{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "parth-port-helm.fullname" }}
  labels:
    {{- include "parth-port-helm.labels" . | nindent 4}}
  annotations:
    {{- range $key, $value:= .Values.ingress.annotations}}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  rules:
    {{- range .Values.ingress.hosts}}
    - host: {{ .host |  quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "parth-port-helm.fullname" . }}
                port:
                  number: 80
          {{- end }}
      {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- end }}