name: Deploy Civo kubernetes pods

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image
      run: |
        SHORT_SHA=$(git rev-parse --short ${{ github.sha }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/parth-port-k8s:$SHORT_SHA .
        docker push ${{ secrets.DOCKER_USERNAME }}/parth-port-k8s:$SHORT_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Install Civo CLI
        uses: civo/action-civo
        with:
          token: ${{ secrets.CIVO_API_KEY }}

      - name: Login to Civo API
        run: civo login --api-key ${{ secrets.CIVO_API_KEY }}

      - name: Deploy to Civo cluster
        run: |
          civo kubernetes apply -f k8s/ --cluster ${{ secrets.CIVO_CLUSTER }}

