name: Update Helm Values

on:
  push:
    paths:
      - '*/Dockerfile'

jobs:
  update-helm-values:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Extract Short SHA
      run: |
        export SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
    - name: Update Helm Values
      run: |
        sed -i "s/kind: .*/kind: \"${SHORT_SHA}\"/" k8s/deployment.yaml
